#EVAL_DATASET_name: "COCO(SigLIP)"
#EVAL_DATASET_name: "COCO(EVA-CLIP)"
#EVAL_DATASET_name: "Flickr30K(SigLIP)"
EVAL_DATASET_name: "Flickr30K(EVA-CLIP)"
#EVAL_DATASET_name: "MSR-VTT"
#EVAL_DATASET_name: "DiDeMo"
#EVAL_DATASET_name: "MSVD"
#EVAL_DATASET_name: "DCI"
#EVAL_DATASET_name: "IIW"
#EVAL_DATASET_name: "Urban1k"
#EVAL_DATASET_name: "ShareGPT4v"
